[project]
name = "pycricodecs"
version = "1.0.0"
description = "acb awb hca parser"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "av>=15.0.0",
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
    "scipy>=1.16.1",
    "tqdm>=4.67.1",
]
