self.payload = {
    'CueTable': [{'CueId': (<UTFTypeValues.uint: 4>, 0), 'ReferenceIndex': (<UTFTypeValues.ushort: 2>, 0), 'Length': (<UTFTypeValues.uint: 4>, 3469), 'ReferenceType': (<UTFTypeValues.uchar: 0>, 3), 'UserData': (<UTFTypeValues.string: 10>, ''), 'Worksize': (<UTFTypeValues.ushort: 2>, 0), 'AisacControlMap': (<UTFTypeValues.bytes: 11>, b''), 'NumAisacControlMaps': (<UTFTypeValues.uchar: 0>, 0), 'HeaderVisibility': (<UTFTypeValues.uchar: 0>, 1)}, {...}, {...}, {...}],
    'CueNameTable': [{'CueName': (<UTFTypeValues.string: 10>, 'vo_adv_0000011_000'), 'CueIndex': (<UTFTypeValues.ushort: 2>, 0)}, {...}, {...}, {...}],
    'WaveformTable': [{'NumSamples': (<UTFTypeValues.uint: 4>, 153012), 'StreamAwbId': (<UTFTypeValues.ushort: 2>, 0), 'MemoryAwbId': (<UTFTypeValues.ushort: 2>, 65535), 'EncodeType': (<UTFTypeValues.uchar: 0>, 2), 'Streaming': (<UTFTypeValues.uchar: 0>, 1), 'NumChannels': (<UTFTypeValues.uchar: 0>, 1), 'LoopFlag': (<UTFTypeValues.uchar: 0>, 1), 'SamplingRate': (<UTFTypeValues.ushort: 2>, 44100), 'ExtensionData': (<UTFTypeValues.ushort: 2>, 65535), 'StreamAwbPortNo': (<UTFTypeValues.ushort: 2>, 0)}, {...}, {...}, {...}],
    'SynthTable': [{'CommandIndex': (<UTFTypeValues.ushort: 2>, 0), 'ReferenceItems': (<UTFTypeValues.bytes: 11>, b'\x00\x01\x00\x00'), 'ControlWorkArea1': (<UTFTypeValues.ushort: 2>, 0), 'ControlWorkArea2': (<UTFTypeValues.ushort: 2>, 0), 'Type': (<UTFTypeValues.uchar: 0>, 0), 'VoiceLimitGroupName': (<UTFTypeValues.string: 10>, ''), 'LocalAisacs': (<UTFTypeValues.bytes: 11>, b''), 'GlobalAisacStartIndex': (<UTFTypeValues.ushort: 2>, 65535), 'GlobalAisacNumRefs': (<UTFTypeValues.ushort: 2>, 0), 'TrackValues': (<UTFTypeValues.bytes: 11>, b''), 'ParameterPallet': (<UTFTypeValues.ushort: 2>, 65535), 'ActionTrackStartIndex': (<UTFTypeValues.ushort: 2>, 65535), 'NumActionTracks': (<UTFTypeValues.ushort: 2>, 0)}, {...}, {...}, {...}],
    'SeqCommandTable': [{'Command': (<UTFTypeValues.bytes: 11>, b"\x00A\x08\x00\x00\x00\x02\x00\x00\x00\x0c\x00E\x04C\x96\x00\x00\x00o\x04\x00\x00\x00\x00\x00o\x04\x00\x03'\x10")}, {...}, {...}, {...}],
    'TrackTable': [{'EventIndex': (<UTFTypeValues.ushort: 2>, 0), 'LocalAisacs': (<UTFTypeValues.bytes: 11>, b'\x00\x00'), 'CommandIndex': (<UTFTypeValues.ushort: 2>, 65535), 'GlobalAisacStartIndex': (<UTFTypeValues.ushort: 2>, 65535), 'GlobalAisacNumRefs': (<UTFTypeValues.ushort: 2>, 0), 'ParameterPallet': (<UTFTypeValues.ushort: 2>, 65535), 'TargetType': (<UTFTypeValues.uchar: 0>, 0), 'TargetName': (<UTFTypeValues.string: 10>, ''), 'TargetId': (<UTFTypeValues.uint: 4>, 4294967295), 'TargetAcbName': (<UTFTypeValues.string: 10>, ''), 'Scope': (<UTFTypeValues.uchar: 0>, 0), 'TargetTrackNo': (<UTFTypeValues.ushort: 2>, 65535)}, {...}, {...}, {...}],
    'SequenceTable': [{'TrackIndex': (<UTFTypeValues.bytes: 11>, b'\x00\x00'), 'CommandIndex': (<UTFTypeValues.ushort: 2>, 0), 'ControlWorkArea1': (<UTFTypeValues.ushort: 2>, 0), 'ControlWorkArea2': (<UTFTypeValues.ushort: 2>, 0), 'PlaybackRatio': (<UTFTypeValues.ushort: 2>, 100), 'NumTracks': (<UTFTypeValues.ushort: 2>, 1), 'LocalAisacs': (<UTFTypeValues.bytes: 11>, b''), 'GlobalAisacStartIndex': (<UTFTypeValues.ushort: 2>, 65535), 'GlobalAisacNumRefs': (<UTFTypeValues.ushort: 2>, 0), 'ParameterPallet': (<UTFTypeValues.ushort: 2>, 65535), 'ActionTrackStartIndex': (<UTFTypeValues.ushort: 2>, 65535), 'NumActionTracks': (<UTFTypeValues.ushort: 2>, 0), 'TrackValues': (<UTFTypeValues.bytes: 11>, b''),
    'Type': (<UTFTypeValues.uchar: 0>, 0)}, {...}, {...}, {...}],
    'BlockSequenceTable': (<UTFTypeValues.bytes: 11>, b''),
    'BlockTable': (<UTFTypeValues.bytes: 11>, b''),
    'EventTable': (<UTFTypeValues.bytes: 11>, b''),
    'ActionTrackTable': (<UTFTypeValues.bytes: 11>, b''),
    'TrackCommandTable': (<UTFTypeValues.bytes: 11>, b''),
    'SynthCommandTable': [{'Command': (<UTFTypeValues.bytes: 11>, b'\x00W\x02\x00e')}, {...}, {...}],
    'TrackEventTable': [{'Command': (<UTFTypeValues.bytes: 11>, b'\x07\xd0\x04\x00\x02\x00\x00\x00\x00\x00')}, {...}, {...}, {...}]
    }